spring:
  application:
    name: Crowdsourced-Waste-Collection-Recycling-System
  jackson:
    time-zone: UTC
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQLHOST:${MYSQL_HOST:mainline.proxy.rlwy.net}}:${MYSQLPORT:${MYSQL_PORT:37671}}/${MYSQLDATABASE:${MYSQL_DATABASE:railway}}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=10000&socketTimeout=60000}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQLUSER:${MYSQL_USER:root}}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQLPASSWORD:${MYSQL_PASSWORD:ndTodFpZUCKFpVehhxHCLbcZXMRHhMYv}}}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

server:
  port: ${PORT:8080}

workrule:
  accept-timeout-hours: 24
  sla-hours: 72
  suspend-threshold: 3
  working-start-hour: 0
  working-end-hour: 23
  reassign-radius-km: 10.0

jwt:
  signerKey: ${JWT_SIGNER_KEY:72d6236b1a543277ad6973b2693a14ab13c437f8749b185a301f5034bbe3de36}
  valid-duration: ${JWT_VALID_DURATION:3600}

open:
  api:
    title: Crowdsourced Waste Collection & Recycling System API
    version: 1.0.0
    description: Tài liệu API cho hệ thống thu gom và tái chế rác thải dựa trên cộng đồng.

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true

app:
  seed:
    enabled: ${APP_SEED_ENABLED:false}
    modular: true
  cors:
    allowed-origins: "${APP_CORS_ALLOWED_ORIGINS:https://crowdsourced-waste-collection-recyc-khaki.vercel.app, https://*.vercel.app, http://localhost:5173}"

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dawzawtbz}
  api-key: ${CLOUDINARY_API_KEY:647161479214626}
  api-secret: ${CLOUDINARY_API_SECRET:vFNgCCXljSShEbrbn7EAls1Lfh0}

vnpt:
  ekyc:
    base-url: ${VNPT_EKYC_BASE_URL:https://api.idg.vnpt.vn}
    access-token: ${VNPT_EKYC_ACCESS_TOKEN:bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmFuc2FjdGlvbl9pZCI6ImM4NTU1YmFkLTc4MTAtNDI1OS05ZDUxLTFiZDc1ZGQxMGZkZiIsInN1YiI6IjAzMWI0YThkLTI4NTQtMTFmMS05ZGUwLTFiN2FjOTQwYTY0YSIsImF1ZCI6WyJyZXN0c2VydmljZSJdLCJ1c2VyX25hbWUiOiJsZWtpZXQuYWFhYTIwMTlAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCJdLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdCIsIm5hbWUiOiJsZWtpZXQuYWFhYTIwMTlAZ21haWwuY29tIiwiZXhwIjoxNzc0NjY2ODM5LCJ1dWlkX2FjY291bnQiOiIwMzFiNGE4ZC0yODU0LTExZjEtOWRlMC0xYjdhYzk0MGE2NGEiLCJhdXRob3JpdGllcyI6WyJVU0VSIl0sImp0aSI6Ijk3YTc2MTIwLWU0YzUtNGYwOS04ZDBmLTkxN2E2OTc5Njk3MyIsImNsaWVudF9pZCI6ImNsaWVudGFwcCJ9.4EGWZegGeTHCDj-1HmYC4q9WMZEdebM4Sq3MZPMcCjfdh5Y-yWQt2MTcaSn5eXzEdKIhTNluca_az8PqlFtYB1TQZklprovnt-6RBW3kuR6r4Nl-G89wHrNx2yDH8PXiKcFDFX_rccWffzMs_sUhbAZS8_0KUqVt9HcKEFQL1XuEqekSa_YJIlFs3K0v-_9MKKqQKAj6tdvnw5OI04zMUDsQjzsVy5kEWVHzqSN-2XZINvI64_jlqNbZJWkP9KqH-oiEI8hptIE2F0X46Kmldx5m_OwZ-QrQGyxWef-xGKUmKvJo13YJsuaJkoSem0uXkrSJWxsS78Jmx6ypZmBXgw}
    token-id: ${VNPT_EKYC_TOKEN_ID:4ddacb2c-0504-19e5-e063-62199f0ae98a}
    token-key: ${VNPT_EKYC_TOKEN_KEY:MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKKniOum9zYzkT087cKaEUlsZM6rj075FYaPaA1NlHjxVODzOAgqpJNRQi3rjPDPKwU2K+z+n2VEagW7WSuracsCAwEAAQ==}
    mac-address: ${VNPT_EKYC_MAC_ADDRESS:TEST1}
    timeout-ms: ${VNPT_EKYC_TIMEOUT_MS:15000}

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
